version: '3.8'

services:
  web:
    build: .
    command:
      - poetry
      - run
      - gunicorn
      - config.wsgi:application
      - --bind
      - 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DATABASE_URL=postgresql://polls_user:polls_password@db:5432/polls_db
    depends_on:
      - db

  test:
    build: .
    command: poetry run pytest
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - SECRET_KEY=test
      - DEBUG=True

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=polls_db
      - POSTGRES_USER=polls_user
      - POSTGRES_PASSWORD=polls_password

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      # .envでHOST_IPが定義されていればその値を使い、
      # なければデフォルト値として127.0.0.1(localhost)を使う
      - "${HOST_IP:-127.0.0.1}:80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
