services:
  web:
    build:
      context: .
      target: production
    image: polls-site-web
    container_name: polls-site-web
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: polls-site-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=polls_db
      - POSTGRES_USER=polls_user
      - POSTGRES_PASSWORD=polls_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  nginx:
    build: ./nginx
    container_name: polls-site-nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "${HOST_IP:-127.0.0.1}:80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: