version: '3.8'

services:
  web:
    build:
      context: .
      target: production
    image: polls-site-web
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db

  test:
    build:
      context: .
      target: builder
    volumes:
      - ./config:/app/config
      - ./manage.py:/app/manage.py
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./tests:/app/tests
    command: sh -c "poetry run pytest"
    environment:
      - POSTGRES_DB=test_polls_db
      - POSTGRES_USER=test_polls_user
      - POSTGRES_PASSWORD=test_polls_password
      - POSTGRES_HOST=db_test
    depends_on:
      - db_test

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=polls_db
      - POSTGRES_USER=polls_user
      - POSTGRES_PASSWORD=polls_password

  db_test:
    image: postgres:15
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test_polls_db
      - POSTGRES_USER=test_polls_user
      - POSTGRES_PASSWORD=test_polls_password

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      # .envでHOST_IPが定義されていればその値を使い、
      # なければデフォルト値として127.0.0.1(localhost)を使う
      - "${HOST_IP:-127.0.0.1}:80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  postgres_test_data:
  static_volume:
