version: '3.8'

services:
  web:
    image: ghcr.io/${{ github.repository }}:latest
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=polls_db
      - POSTGRES_USER=polls_user
      - POSTGRES_PASSWORD=polls_password

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "${HOST_IP:-127.0.0.1}:80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
