name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  format-and-lint:
    uses: ./.github/workflows/format-and-lint.yml

  build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-and-push-image.yml
    secrets: inherit

  run-tests:
    needs: build-and-push-image
    uses: ./.github/workflows/run-tests.yml
    with:
      image-tag: ${{ needs.build-and-push-image.outputs.image-tag }}