name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  format-and-lint:
    uses: ./.github/workflows/format-and-lint.yml

  docker-build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yml

  run-tests:
    needs: docker-build
    uses: ./.github/workflows/run-tests.yml