name: Build and Push Docker Image

on:
  workflow_call:
    outputs:
      image-tag:
        description: "The tag of the built and pushed Docker image."
        value: ${{ jobs.build-and-push.outputs.image-tag }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save Docker image
        run: |
          docker save $(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1) -o polls-site-image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: polls-site-image
          path: polls-site-image.tar
          retention-days: 3