name: Format and Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build builder image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          target: builder
          load: true
          tags: polls-site-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Ruff Linter
        run: make lint

      - name: Run Black Formatter Check
        run: make format-check
