# .github/workflows/run-tests.yml
name: Run Tests

on:
  workflow_call:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install and configure Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true
          
      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Django Tests
        run: |
          poetry run python manage.py test