name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: docker-compose run --rm test
        env:
          SECRET_KEY: "test-secret-key-for-ci"
          DEBUG: "False"