name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.example .env

      - name: Start services
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose exec web poetry run pytest