name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Django Tests in Docker Container
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} python manage.py test