name: Run Tests

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: polls-site-image

      - name: Load Docker image
        run: |
          docker load -i polls-site-image.tar

      - name: Run Django Tests in Docker Container
        run: |
          docker run --rm ${{ inputs.image-tag }} poetry run python manage.py test