name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build builder image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          target: builder
          load: true
          tags: polls-site-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create .env file
        run: make setup

      - name: Run tests
        run: make test